# Generated by Django 3.1 on 2020-08-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_message',
            field=models.TextField(default='this is an empty post body'),
        ),
    ]
